lint:
  rules:
    no_default: true
    add:
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - FILE_NAMES_LOWER_SNAKE_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - IMPORTS_SORTED
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - ORDER
      - PACKAGE_NAME_LOWER_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - REPEATED_FIELD_NAMES_PLURALIZED
      - QUOTE_CONSISTENT
      - INDENT
      - PROTO3_FIELDS_AVOID_REQUIRED
      - PROTO3_GROUPS_AVOID
      - SERVICE_NAMES_END_WITH
      - FIELD_NAMES_EXCLUDE_PREPOSITIONS
      #      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS
      - RPC_NAMES_CASE
      - SYNTAX_CONSISTENT
      # disabled rules
  #      - MAX_LINE_LENGTH
  #      - MESSAGES_HAVE_COMMENT
  #      - SERVICES_HAVE_COMMENT
  #      - RPCS_HAVE_COMMENT
  #      - FIELDS_HAVE_COMMENT
  #      - ENUMS_HAVE_COMMENT
  #      - ENUM_FIELDS_HAVE_COMMENT
  #      - FILE_HAS_COMMENT

  rules_option:
    indent:
      not_insert_newline: true
    repeated_field_names_pluralized:
      uncountable_rules:
        - ((.*)+_list)
    field_names_exclude_prepositions:
      excludes: [at, by, for, of, from, to, with, To]
    message_names_exclude_prepositions:
      excludes: [ at, by, for, of, from, to, with, To]