version: "3"

services:
  app-server:
    container_name: "grpc-weather-server"

    networks:
      - back

  app-client:
    container_name: "grpc-weather-client"

    networks:
      - back

networks:
  back:
    driver: bridge
